### ISSUE TITLE
SpiNNaker start/stop

### ISSUE THREAD

**Issue by arrenglover** [event-driven-robotics/HPU_Core#1]
Additional Feature - 

the Spinnaker core can be enabled/disabled externally by a specific message packet arriving from the device (SpiNNaker board). This allows the SpiNNaker to control when it is ready for processing itself. Sending events while the board is booting/loading causes the SpiNNaker failure.

The values of these registers should be programmable through register values:

Default values for the registers/packet format:
0x80000000 = active (send events through the SpiNNaker)
0x40000000 = disabled (do not send events to the SpiNNaker)

Alternative - 
The zynqGrabber software could implement this functionality. However the DMA pool-size needs to be dynamic such that the single data packet is passed through to the zynqGrabber without having to wait for the entire pool-size to be read.

**Comment by mcasti-iit** [comment]
This function is available from **HPU Core 3.1 Rev4 (Beta 1)**;
START/STOP key command are defined in W/R registers:
- SpiNNlink Start command key (SPNN_START_KEY_REG) at address (HPUCore Base + 0x80), default value 0x80000000
- SpiNNlink Stop command key (SPNN_STOP_KEY_REG) at address (HPUCore Base + 0x82), default value 0x40000000

Please NOTE: the Address Bus has been enlarged from 7 bits to 8 bits.

**Comment by arrenglover** [comment]
Let me know what you need to do to test this with the SpiNNaker. I have updated my code to perform such that it should send the "start" and "stop" commands

**Comment by mcasti-iit** [comment]
Go to page 
https://github.com/event-driven-robotics/zynq-spinnakerlink/releases/tag/v2.0_B3__(HPU_3.1_Rev4_B1)
and download the **BOOT.bin** file.
You can find Register information in **HPU Core 3.1 - User Guide - RevB.pdf** file.
Please note that the width of bus address has been enlarged to 8 bit (hopefully it doesn't require a software upgrade as well)

**Comment by mcasti-iit** [comment]
That sounds very strange, Arren.
The Dump flag, now, can be set to one only on those cases:


-          An AXI bus reset occurrence (driven by Zynq)

-          A missing acknowledge signal from SpiNNaker during transmission attempts.

When “dump” is zero, does TX path work properly?

Maurizio

**Comment by arrenglover** [comment]
The most recent tests show this is working
