### ISSUE TITLE
More flexible blocking read in driver/hpu

### ISSUE THREAD

**Issue by arrenglover** [event-driven-robotics/HPU_Core#5]
_note_: I added the issue here to keep it with other issues for development of the HPU for spinnaker. However it might involve changes to both the HPU code and the driver code. If needed we can move it to the repository of the driver.

**Issue:**
Currently the driver is constrained to read a fixed amount of data defined by a parameter in function to read from the device ( `int read(fd, buffer, size)` ). 
- The value of size can be set to be small so the function returns quickly, but this is slow when there is lots of data to read (sending many small packets over the network)
- The value of size can be set larger, but this introduces delay and stutter when there isn't many events.

The current implementation in the zynqGrabber is to have two threads. One reading data from the driver with a small buffer size, such that it returns quickly. One which integrates the small chunks into a large packet to send. 
- with more threads running it is more likely that one thread gets blocked for a longer than expected time (depending on OS scheduling). This manifests as stutter in the event-stream. Recently this has become worse (I think there might have been some change in the YARP thread class?)
- With the HPU spinnaker both reading and writing, there are even more threads running on the 2 core cpu and the stutter is even more noticable.

**Solution:**
The driver read call could be made more flexible for both small and large reads with the following behaviour:
- if read is called and there is no data, read blocks and waits for _some_ data. When data is received that data is loaded into the buffer and read returns.
- if read is called and the amount of data available <= size. That data is loaded into the buffer and read returns
- if read is called and the amount of data available >= size. An amount of data equal to size is loaded into the buffer and read returns.

In this way, read can be called by the zynqGrabber with a large buffer size and, even if there is only a small amount of data, will still be responsive. The two threads can be collapsed into one, and the event-stream should become smoother and more consistent. It may require a flag from the HPU to say if data is available or not?

**Comment by arrenglover** [comment]
In addition, during this update, the time-out for the call to read should be reduced from 1 minute to 15 seconds

**Comment by andreamerello** [comment]
I can make change the read() behaviour as per your request, but I think it would be not very effective indeed.

The problem is that the driver receives data in big chunks (i.e. the DMA transfers big data blocks), so that you would be blocked on read() until a big data block has been received.

The problem is that if we decrease the DMA data block size then we can handle well situation in which we have few data but we would fail to handle situations in which a lot of data is flowing (i.e. HPU rx fifo full error).

The solution would be implementing a kind of dynamic, adaptive, mechanism; but it is not that easy (not sure if it is even feasible or at least convenient with current HW)..

**Comment by arrenglover** [comment]
Maybe I don't have all the information about how the DMA and the driver interact. I assume that the "read" call of the driver is decoupled from the DMA loading data into memory that the driver can access. Therefore the DMA is loading data asynchronously (in pool-sized chunks), and only when "read" is called that the driver accesses that data and passes it on to the application that called "read"?

My application (_zynqGrabber_) calls ``int r = read(fd, buffer, bytes_to_read)``, where ``bytes_to_read = 20480`` and ``pool-size = 1024``. If I use a smaller value of ``bytes_to_read`` I experience delays and data-loss due to the network.

The current read function forces me to wait until the entire ``bytes_to_read`` amount of data is available before it returns. That means there is 20 DMA operations before I can access the data. If there is already 20 DMA chunk available then it is fine because I have a lot of data to push to the network immediately. If the data rate is slower, and say there is only 1 DMA chunk available when I call ``read``, it would be nice if the driver returns with just that data. So I can send it.

My work-around to this issue is to have a multi-threaded application to handle reading (from the driver) and writing (to the network) asynchronously, but the thread scheduling has been causing problems recently. It also seems like overkill if I can have a more flexible ``read`` call to solve the same problem.

An alternative solution is: if I can ask the driver how much data is currently available before calling ``read``, I can alter how much data I will ask for.

**Comment by andreamerello** [comment]
I confirm that the DMA works as you said.

Ok, if you ask so much data to read() - that is, much more than the DMA chunk size - then changing the read() as you asked for should indeed have effect.

**Comment by arrenglover** [comment]
okay great! thanks 👍 

I would also say that having a dynamic DMA would be good for when we have to switch between vision and skin, as they have very different data-rates, and we have to change the pool-size to suit. However, current applications aren't mixing the sensors. Once we have both event-driven vision and event-driven skin together, there might be some circumstances when the high pool-size used for vision affects the responsiveness of the skin. 

It's for a different issue though 😉
